### PR TITLE
update to 3.3a

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review. I added myself as a maintainer, I hope that's ok.

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
thanks!

**Comment by matthiasdiener** [comment]
For some reason, anaconda thinks that 3.3 is newer than 3.3a and still installs the older 3.3 by default 😞  (see e.g. the version number shown here https://anaconda.org/conda-forge/tmux)

**Pull request merged**
