### PR TITLE
update pinnings

### PR DESCRIPTION
**Pull request by dougalsutherland**
Also replace the pinnings with the current ones from https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py (which are slightly more specific), do a tiny bit of recipe cleanup, and add myself as a maintainer.

There's also a 2.5 release, which I'll send in after this one (might as well get all the major releases built...).

### CODE REVIEW

**Comment by dougalsutherland** [comment]
Travis is obviously going to be a while right now, but FWIW this builds locally on my Mac.

**Comment by jakirkham** [comment]
Should we do a build number bump with the pinning changes first? Also is there any reason not to just skip to 2.5?

**Comment by dougalsutherland** [comment]
tmux sometimes has incompatible changes, but it looks like it didn't actually from 2.4 to 2.5: [changelog](https://github.com/tmux/tmux/blob/master/CHANGES). So sure, I'll change this PR to make the other changes but keep it at 2.3.

**Comment by dougalsutherland** [comment]
The Travis build did eventually pass, so this is now a gentle ping. :)

**Pull request merged**
